Data Preprocessing

Locating Python

In [835]:
import sys
locate_python = sys.exec_prefix
print(locate_python)

c:\Users\janie\anaconda3


Import Libraries and Dataset

In [836]:
import numpy as np
import pandas as pd 

In [837]:
dataset = pd.read_csv(r"C:\Users\janie\OneDrive\Desktop\3-Year_Recidivism_for_Offenders_Released_from_Prison_in_Iowa.csv")
dataset

Fiscal Year Released  Recidivism Reporting Year Age At Release  \
0                      2010                       2013          25-34   
1                      2010                       2013          25-34   
2                      2010                       2013          35-44   
3                      2010                       2013          25-34   
4                      2010                       2013          35-44   
...                     ...                        ...            ...   
26015                  2015                       2018       Under 25   
26016                  2015                       2018          35-44   
26017                  2015                       2018          25-34   
26018                  2015                       2018          25-34   
26019                  2015                       2018          35-44   

       Days to Return                        Release Type  \
0                 433                              Parole   
1                 453       Discharged or End of Sentence   
2                 832                              Parole   
3                   0                              Parole   
4                 116       Discharged or End of Sentence   
...               ...                                 ...   
26015               0           Paroled to Detainer - INS   
26016               0        Released to Special Sentence   
26017               0                      Parole Granted   
26018               0       Paroled w/Immediate Discharge   
26019             369  Paroled to Detainer - Out of State   

           Race - Ethnicity     Sex  Offense Classification  Offense Type  \
0      Black - Non-Hispanic    Male                C Felony       Violent   
1      White - Non-Hispanic    Male                D Felony      Property   
2      White - Non-Hispanic    Male                B Felony          Drug   
3      White - Non-Hispanic    Male                B Felony         Other   
4      Black - Non-Hispanic    Male                D Felony       Violent   
...                     ...     ...                     ...           ...   
26015      White - Hispanic    Male                C Felony       Violent   
26016  White - Non-Hispanic    Male                C Felony       Violent   
26017  White - Non-Hispanic  Female  Aggravated Misdemeanor  Public Order   
26018  White - Non-Hispanic    Male                D Felony      Property   
26019  White - Non-Hispanic    Male                D Felony       Violent   

           Offense Subtype Return to Prison Recidivism Type  \
0                  Robbery              Yes             New   
1                    Theft              Yes            Tech   
2              Trafficking              Yes            Tech   
3           Other Criminal               No   No Recidivism   
4                  Assault              Yes            Tech   
...                    ...              ...             ...   
26015              Assault               No   No Recidivism   
26016                  Sex               No   No Recidivism   
26017              Traffic               No   No Recidivism   
26018                Theft               No   No Recidivism   
26019  Murder/Manslaughter              Yes            Tech   

      New Offense Classification New Offense Type New Offense Sub Type  \
0                       C Felony             Drug          Trafficking   
1                              0                0                    0   
2                              0                0                    0   
3                              0                0                    0   
4                              0                0                    0   
...                          ...              ...                  ...   
26015                          0                0                    0   
26016                          0                0                    0   
26017                          0                0

In [838]:
dataset.shape

(26020, 16)

In [839]:
column_names = dataset.columns.values.tolist()
column_names

['Fiscal Year Released',
 'Recidivism Reporting Year',
 'Age At Release',
 'Days to Return',
 'Release Type',
 'Race - Ethnicity',
 'Sex',
 'Offense Classification',
 'Offense Type',
 'Offense Subtype',
 'Return to Prison',
 'Recidivism Type',
 'New Offense Classification',
 'New Offense Type',
 'New Offense Sub Type',
 'Target Population']

In [840]:
x = dataset[['Fiscal Year Released','Recidivism Reporting Year','Release Type',
'Race - Ethnicity','Age At Release','Sex','Offense Classification','Offense Type','Offense Subtype',
'Return to Prison','Days to Return','Recidivism Type','New Offense Classification','New Offense Type',
'New Offense Sub Type','Target Population']].values
x

array([[2010, 2013, 'Parole', ..., 'Drug', 'Trafficking', 'Yes'],
       [2010, 2013, 'Discharged or End of Sentence', ..., '0', '0', 'No'],
       [2010, 2013, 'Parole', ..., '0', '0', 'Yes'],
       ...,
       [2015, 2018, 'Parole Granted', ..., '0', '0', 'No'],
       [2015, 2018, 'Paroled w/Immediate Discharge', ..., '0', '0',
        'Yes'],
       [2015, 2018, 'Paroled to Detainer - Out of State', ..., 'Violent',
        'Murder/Manslaughter', 'Yes']], dtype=object)

In [841]:
y = dataset[["Recidivism Type"]].values
y 

array([['New'],
       ['Tech'],
       ['Tech'],
       ...,
       ['No Recidivism'],
       ['No Recidivism'],
       ['Tech']], dtype=object)

Find Missing Values

In [842]:
from sklearn.impute import SimpleImputer
import numpy as np

In [843]:
imputer = SimpleImputer(strategy = 'mean')

In [844]:
imputer = imputer.fit_transform(x[:,0:2])
x

array([[2010, 2013, 'Parole', ..., 'Drug', 'Trafficking', 'Yes'],
       [2010, 2013, 'Discharged or End of Sentence', ..., '0', '0', 'No'],
       [2010, 2013, 'Parole', ..., '0', '0', 'Yes'],
       ...,
       [2015, 2018, 'Parole Granted', ..., '0', '0', 'No'],
       [2015, 2018, 'Paroled w/Immediate Discharge', ..., '0', '0',
        'Yes'],
       [2015, 2018, 'Paroled to Detainer - Out of State', ..., 'Violent',
        'Murder/Manslaughter', 'Yes']], dtype=object)

Encoding Categorical Data

In [845]:
# Manually completed through CSV file

Splitting Data into Training/Test

In [855]:
from sklearn.model_selection import train_test_split

In [856]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [857]:
x_train

array([[2011, 2014, 'Parole', ..., '0', '0', 'No'],
       [2013, 2016, 'Discharged - Expiration of Sentence', ...,
        'Property', 'Theft', 'No'],
       [2015, 2018, 'Discharged - Expiration of Sentence', ..., '0', '0',
        'Yes'],
       ...,
       [2012, 2015, 'Parole', ..., 'Drug', 'Drug Possession', 'Yes'],
       [2012, 2015, 'Discharged or End of Sentence', ..., '0', '0', 'No'],
       [2010, 2013, 'Parole', ..., '0', '0', 'Yes']], dtype=object)

In [858]:
x_test

array([[2013, 2016, 'Parole Granted', ..., 'Drug', 'Drug Possession',
        'Yes'],
       [2015, 2018, 'Parole Granted', ..., '0', '0', 'No'],
       [2012, 2015, 'Parole', ..., '0', '0', 'Yes'],
       ...,
       [2013, 2016, 'Discharged - Expiration of Sentence', ..., '0', '0',
        'No'],
       [2012, 2015, 'Discharged or End of Sentence', ..., 'Violent',
        'Robbery', 'No'],
       [2015, 2018, 'Parole Granted', ..., '0', '0', 'Yes']], dtype=object)

In [859]:
y_train

array([1, 0, 1, ..., 0, 1, 1])

In [860]:
y_test

array([0, 1, 2, ..., 1, 0, 1])