# <b> Test Multi Logit Model 1 <b>

## Multinomial Logistic Regression Model using using Age, Race, Sex, and Prior Arrests as Features <b>

Load Necessary Libraries

In [154]:
import pandas as pd
import numpy as np
import scipy as scp
import sklearn
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import confusion_matrix

Read Dataset

In [155]:
# reading dataset using pandas
data = pd.read_csv(r'georgia_rec_clean.csv')
# print data
data

Supervision_Risk_Score_First  Prison_Offense  Gender  Race  \
0                               3.0             0.0     1.0   0.0   
1                               6.0             3.0     1.0   0.0   
2                               7.0             0.0     1.0   0.0   
3                               7.0             2.0     1.0   1.0   
4                               4.0             3.0     1.0   1.0   
...                             ...             ...     ...   ...   
25830                           5.0             5.0     1.0   0.0   
25831                           5.0             5.0     1.0   1.0   
25832                           5.0             5.0     1.0   0.0   
25833                           5.0             5.0     0.0   1.0   
25834                           5.0             5.0     1.0   1.0   

       Age_At_Release  Education_Level  Dependents  \
0                 5.0              0.0         3.0   
1                 3.0              2.0         1.0   
2                 6.0              0.0         3.0   
3                 4.0              2.0         1.0   
4                 3.0              2.0         3.0   
...               ...              ...         ...   
25830             1.0              0.0         1.0   
25831             4.0              0.0         3.0   
25832             3.0              0.0         3.0   
25833             3.0              0.0         3.0   
25834             2.0              1.0         3.0   

       Prior_Arrest_Episodes_Misd  Prior_Arrest_Episodes_Violent  \
0                             6.0                            1.0   
1                             6.0                            3.0   
2                             6.0                            3.0   
3                             6.0                            0.0   
4                             4.0                            3.0   
...                           ...                            ...   
25830                         2.0                            2.0   
25831                         2.0                            0.0   
25832                         0.0                            0.0   
25833                         0.0                            0.0   
25834                         6.0                            0.0   

       Prior_Conviction_Episodes_Felony  ...  Prior_Conviction_Episodes_Drug  \
0                                   3.0  ...                             2.0   
1                                   3.0  ...                             2.0   
2                                   3.0  ...                             2.0   
3                                   3.0  ...                             2.0   
4                                   1.0  ...                             1.0   
...                                 ...  ...                             ...   
25830                               0.0  ...                             0.0   
25831                               0.0  ...                             0.0   
25832                               0.0  ...                             0.0   
25833                               0.0  ...                             0.0   
25834                               1.0  ...                             0.0   

       Prior_Arrest_Episodes_GunCharges  Prior_Conviction_Episodes_Viol  \
0                                   0.0                             0.0   
1                                   0.0                             1.0   
2                                   0.0                             1.0   
3                                   0.0                             0.0   
4                                   0.0                             1.0   
...                                 ...                             ...   
25830                               0.0                             1.0   
25831                               0.0                             0.0   
25832                               0.0                             0.0   
2

In [156]:
x1 = data[['Age_At_Release', 'Race', 'Gender', 'Supervision_Risk_Score_First','Prior_Arrest_Episodes_Violent',
           'Prior_Arrest_Episodes_GunCharges', 'Prior_Arrest_Episodes_Felony', 'Prior_Arrest_Episodes_Property',
           'Prior_Arrest_Episodes_Drug', 'Prior_Arrest_Episodes_Misd']]
y1 = data[['Recidivism_Within_3years']]

Spliting the Dataset

In [157]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.20, random_state=5)

In [158]:
print(x_train1.shape)
print(x_test1.shape)
print(y_train1.shape)
print(y_test1.shape)

(20668, 10)
(5167, 10)
(20668, 1)
(5167, 1)


In [159]:
y_train1 = y_train1.values.ravel()

Building the Multi Logit Model

In [160]:
model1 = LogisticRegression(random_state=5, multi_class='multinomial', penalty='none', solver='newton-cg').fit(x_train1, y_train1)

In [161]:
pred1 = model1.predict(x_test1)

In [162]:
param = model1.get_params()
print(param)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'none', 'random_state': 5, 'solver': 'newton-cg', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


Print Model Parameters

In [163]:
print('Intercept: \n', model1.intercept_)
print('Coefficients: \n', model1.coef_)

Intercept: 
 [-0.31184351]
Coefficients: 
 [[-0.15376289  0.00380416  0.25348239  0.01763949  0.04821537  0.02006951
   0.00304216  0.11159115  0.04120205  0.06474131]]


Calculate Odds Ratio Estimates

In [164]:
np.exp(model1.coef_)

array([[0.85747532, 1.00381141, 1.28850469, 1.01779598, 1.04939664,
        1.02027225, 1.00304679, 1.11805565, 1.04206263, 1.066883  ]])

Statsmodels to Assess Variables

In [165]:
np.asarray(data)

array([[3., 0., 1., ..., 3., 3., 2.],
       [6., 3., 1., ..., 0., 3., 0.],
       [7., 0., 1., ..., 2., 2., 1.],
       ...,
       [5., 5., 1., ..., 0., 0., 0.],
       [5., 5., 0., ..., 0., 0., 0.],
       [5., 5., 1., ..., 2., 1., 1.]])

In [166]:
logit_model1 = sm.MNLogit(y_train1, sm.add_constant(x_train1))

In [167]:
result = logit_model1.fit()
stats1 = result.summary()
stats2 = result.summary2()
print(stats1)
print(stats2)

Optimization terminated successfully.
         Current function value: 0.616079
         Iterations 5
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                20668
Model:                        MNLogit   Df Residuals:                    20657
Method:                           MLE   Df Model:                           10
Date:                Sun, 07 May 2023   Pseudo R-squ.:                 0.09540
Time:                        11:40:29   Log-Likelihood:                -12733.
converged:                       True   LL-Null:                       -14076.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                             y=1       coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                               -0.6237      0.079     -7.92

In [168]:
class_report = classification_report(y_test1, pred1)
print(class_report)

              precision    recall  f1-score   support

         0.0       0.65      0.43      0.52      2201
         1.0       0.66      0.82      0.73      2966

    accuracy                           0.66      5167
   macro avg       0.65      0.63      0.63      5167
weighted avg       0.66      0.66      0.64      5167



Overfitting vs Underfitting

In [169]:
print("Training set score: {:.4f}".format(model1.score(x_train1, y_train1)))
print("Test set score: {:.4f}".format(model1.score(x_test1, y_test1)))

Training set score: 0.6644
Test set score: 0.6576


Metrics Analysis

In [170]:
y_pred1 = model1.predict(x_test1)

In [171]:
cm1 = confusion_matrix(y_test1, y_pred1)
print(cm1)

[[ 954 1247]
 [ 522 2444]]


# <b> Test Multi Logit Model 2 <b>

### <b> Multi Logit Model using using Age, Sex, and Prior Convictions as Features <b>

Feature Selection

In [172]:
x2 = data[['Age_At_Release', 'Gender', 'Prison_Offense', 'Prior_Conviction_Episodes_Felony', 
      'Prior_Conviction_Episodes_Misd', 'Prior_Conviction_Episodes_Drug', 'Prior_Conviction_Episodes_PPViolationCharges',
      'Prior_Conviction_Episodes_DomesticViolenceCharges', 'Prior_Conviction_Episodes_Prop']]
y2 = data[['Recidivism_Within_3years']]

Splitting Dataset

In [173]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(x2, y2, test_size=0.20, random_state=5)

In [174]:
print(x_train2.shape)
print(x_test2.shape)
print(y_train2.shape)
print(y_test2.shape)

(20668, 9)
(5167, 9)
(20668, 1)
(5167, 1)


In [175]:
y_train2 = y_train2.values.ravel()

Predict Classification

In [176]:
model2 = LogisticRegression(random_state=5, multi_class='multinomial', penalty='none', solver='newton-cg').fit(x_train2, y_train2)

In [177]:
pred2 = model2.predict(x_test2)

In [178]:
param2 = model2.get_params()
print(param2)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'none', 'random_state': 5, 'solver': 'newton-cg', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


Print Model Parameters

In [179]:
print('Intercept: \n', model2.intercept_)
print('Coefficients: \n', model2.coef_)

Intercept: 
 [-0.02458632]
Coefficients: 
 [[-0.16183878  0.25627883 -0.00636164  0.07343565  0.0988418   0.03659797
   0.00844213  0.06971304  0.13002693]]


Calculate Odds Ratio Estimates

In [180]:
np.exp(model2.coef_)

array([[0.85057832, 1.29211296, 0.99365856, 1.07619928, 1.10389165,
        1.03727593, 1.00847786, 1.07220046, 1.13885905]])

Statsmodels to Assess Variables

In [181]:
np.asarray(data)

array([[3., 0., 1., ..., 3., 3., 2.],
       [6., 3., 1., ..., 0., 3., 0.],
       [7., 0., 1., ..., 2., 2., 1.],
       ...,
       [5., 5., 1., ..., 0., 0., 0.],
       [5., 5., 0., ..., 0., 0., 0.],
       [5., 5., 1., ..., 2., 1., 1.]])

In [182]:
logit_model2 = sm.MNLogit(y_train2, sm.add_constant(x_train2))

In [183]:
result2 = logit_model2.fit()
stats1 = result2.summary()
stats2 = result2.summary2()
print(stats1)
print(stats2)

Optimization terminated successfully.
         Current function value: 0.622355
         Iterations 5
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                20668
Model:                        MNLogit   Df Residuals:                    20658
Method:                           MLE   Df Model:                            9
Date:                Sun, 07 May 2023   Pseudo R-squ.:                 0.08619
Time:                        11:40:31   Log-Likelihood:                -12863.
converged:                       True   LL-Null:                       -14076.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                                              y=1       coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------
const                         

Overfitting vs Underfitting

In [184]:
print("Training set score: {:.4f}".format(model2.score(x_train2, y_train2)))
print("Test set score: {:.4f}".format(model2.score(x_test2, y_test2)))

Training set score: 0.6583
Test set score: 0.6542


Metrics Analysis

In [185]:
from sklearn.metrics import classification_report
y_pred2 = model2.predict(x_test2)

In [186]:
report2 = classification_report(y_test2, y_pred2)
print(report2)

              precision    recall  f1-score   support

         0.0       0.65      0.41      0.50      2201
         1.0       0.66      0.83      0.73      2966

    accuracy                           0.65      5167
   macro avg       0.65      0.62      0.62      5167
weighted avg       0.65      0.65      0.64      5167

